### ISSUE TITLE
Addon options not read from ENV

### ISSUE THREAD

**Issue by kcmr** [dunnkers/ember-polymer#131]
Hi,

I'm using your addon in applications using Ember 3.3.0 and Ember 3.5.1 and options ([config variables](https://github.com/dunnkers/ember-polymer#config-variables)) are not read from environment.

I have little experience with Ember and I'm not sure if this is the proper way of getting the addon options from ENV, so this is why I'm opening this issue instead of a Pull Request.

Replacing `app.options` by `app.project.config()` in lib/config seems to work.

```js
const addonOptions = app.project.config()['ember-polymer'] || {};
```

Is this ok? Thank you in advance.

**Comment by dunnkers** [comment]
Will look into this

**Comment by dunnkers** [comment]
Makes sense. I think some things changed though. Will add comment.

**Comment by dunnkers** [comment]
And thanks for the report by the way!
