### ISSUE TITLE
Support for polymer 2.

### ISSUE THREAD

**Issue by kosmonaffft** [dunnkers/ember-polymer#62]
Hello...

Is support for polymer 2 planning?

**Comment by dunnkers** [comment]
Hello @kosmonaffft, Polymer 2 support is certainly planned! You can expect this soon. And thanks for using the addon, feedback is appreciated!

**Comment by dunnkers** [comment]
Progress is tracked in the [2.0 branch](https://github.com/dunnkers/ember-polymer/tree/2.0).

**Comment by dunnkers** [comment]
2.0 support is out but in [prerelease](https://github.com/dunnkers/ember-polymer/releases)! Checklist for 2.0 release is tracked in issue https://github.com/dunnkers/ember-polymer/issues/74.
