### ISSUE TITLE
Use Native Css properties

### ISSUE THREAD

**Issue by sergicontre** [dunnkers/ember-polymer#76]
Hi!

Is there any way to tell you through configuration the use of css native properties?

For default is 'undefined' in Polymer.Settings:

I need this:

window.Polymer = {
        dom: 'shadow',
        lazyRegister: true,
        useNativeCSSProperties: true
      };

Thanks!

Regards!!

**Comment by dunnkers** [comment]
Hey @sergicontre ! Nice to see you've found my repo.

You are referring to Global Polymer Settings, as described here:
[https://www.polymer-project.org/1.0/docs/devguide/settings](https://www.polymer-project.org/1.0/docs/devguide/settings)

Those are only for Polymer 1.0, the ones for 2.0 are stated here, which have a lot less options:
[https://www.polymer-project.org/2.0/docs/devguide/settings](https://www.polymer-project.org/2.0/docs/devguide/settings)

You are aware of this difference right? Are you working with Polymer 1.0 or 2.0?

Anyway, I will integrate a simple option soon to include those settings. Do note that you can really easily enable those options by putting this in your `<head>`:

```html
  <script>
    window.Polymer = {
        dom: 'shadow',
        lazyRegister: true,
        useNativeCSSProperties: true
    };
  </script>
```

**Comment by dunnkers** [comment]
Got this feature in both `v1.x` and `v2.x` of my addon. 🤩 See the (Releases)[https://github.com/dunnkers/ember-polymer/releases] page for details.

**Comment by sergicontre** [comment]
Actually I am working with both versions: D.

The problem was that the installation of ember-polymer installed version 1.0.1 which could not activate the use of native CSS properties.

Thank you!!

**Comment by dunnkers** [comment]
Glad it's resolved! Don't forget to star ⭐️ the repo!

**Comment by sergicontre** [comment]
Done! Thank you!
